# Generated by Django 4.2.11 on 2026-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airequest',
            name='mode',
            field=models.CharField(choices=[('explain', 'Explain'), ('quiz', 'Quiz'), ('summarize', 'Summarize'), ('examples', 'Examples')], default='explain', max_length=10),
        ),
        migrations.AddField(
            model_name='airequest',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airequest',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
